### ISSUE TITLE
[BUG]: installation fail

### ISSUE THREAD

**Issue by Mohadib2** [Athena-OS/athena#104]
### Athena OS version

athena-rolling

### Which environment or technology are you using?

- [X] Baremetal
- [ ] VirtualBox Virtual Machine
- [ ] VMware Virtual Machine
- [ ] Hyper-V Virtual Machine
- [ ] QEMU/KVM
- [ ] Parallels
- [ ] UTM
- [ ] Container
- [ ] WSL

### Repro steps

hello 
i have problem installing the latest iso
the installation ends with errors of levon signature
in the live environment i managed to fix the problem and installed keyring and run pacman -Syu and all ran well 
but when installed to to hd i got the errors again and it seems setup didnot install lot of needed packages include the grub and i cant boot to the system.

i tried to follow this article 
https://wiki.archlinux.org/title/GRUB

mount the linux partition to /mnt
mount the boot partition to the /mnt/boot
chroot to /mnt
**there where lot of missing binaries even nano was not there so i copy it from the live /bin**
tried to install grub and efibootmgr bot the lovon error prevented me to do so.

strap.sh fix did not work
tried 
comment out everything in /etc/pacman.d/mirrorlist, add Server = https://www.blackarch.org/ at the bottom, run pacman -Scc, pacman-key --refresh-keys and  pacman -Syy

rm /var/lib/pacman/sync/blackarch.db.sig
pacman-key --init 
pacman-key --populate

no luck
siglevel = optional trustall

still getting the same error 

any suggestions?
thank you

### Expected behavior

install correctly

### Actual behavior

install fail

**Comment by D3vil0p3r** [comment]
Before running the install, download https://github.com/BlackArch/blackarch-site/blob/master/strap.sh and run it. If no errors are produced, run the installer.

**Comment by D3vil0p3r** [comment]
I uploaded a new ISO where I removed BA mirrors. Download it and try.

**Comment by HHhne** [comment]
INFO ] 19:12:16 :: Synchronizing package databases...
[ [38;5;196mERROR[0m ] 19:12:16 pacman err (exit code 1): error: failed to synchronize all databases (no servers configured for repository)
[ [38;5;196mERROR[0m ] 19:12:16 The package manager failed with exit code: 1
[ INFO ] 19:12:16 The system has 8 cores
[ INFO ] 19:12:16 Sed '#MAKEFLAGS=.*' to 'MAKEFLAGS="-j8"' in file /mnt/etc/makepkg.conf
[ INFO ] 19:12:16 Set available cores on MAKEFLAGS
[ INFO ] 19:12:16 Sed '#BUILDDIR=.*' to 'BUILDDIR=/tmp/makepkg' in file /mnt/etc/makepkg.conf
[ INFO ] 19:12:16 Improving compilation times
[ INFO ] 19:12:16 Sed 'COMPRESSXZ=\(xz -c -z -\)' to 'COMPRESSXZ=(xz -c -z - --threads=0)' in file /mnt/etc/makepkg.conf
[ INFO ] 19:12:16 Changing the compression settings
[ INFO ] 19:12:16 Sed 'COMPRESSZST=\(zstd -c -z -q -\)' to 'COMPRESSZST=(zstd -c -z -q - --threads=0)' in file /mnt/etc/makepkg.conf
[ INFO ] 19:12:16 Changing the compression settings
[ INFO ] 19:12:16 Sed 'PKGEXT='.pkg.tar.xz'' to 'PKGEXT='.pkg.tar.zst'' in file /mnt/etc/makepkg.conf
[ INFO ] 19:12:16 Changing the compression settings
[ INFO ] 19:12:16 AMD CPU detected.
[ INFO ] 19:12:16 :: Synchronizing package databases...
[ [38;5;196mERROR[0m ] 19:12:16 pacman err (exit code 1): error: failed to synchronize all databases (no servers configured for repository)
[ [38;5;196mERROR[0m ] 19:12:16 The package manager failed with exit code: 1
[ INFO ] 19:12:16 :: Synchronizing package databases...
[ [38;5;196mERROR[0m ] 19:12:16 pacman err (exit code 1): error: failed to synchronize all databases (no servers configured for repository)
[ [38;5;196mERROR[0m ] 19:12:16 The package manager failed with exit code: 1
[ INFO ] 19:12:17 Enable vmware-vmblock-fuse
[ INFO ] 19:12:17 Enable vmtoolsd
sed: can't read /mnt/etc/mkinitcpio.conf: No such file or directory
[ INFO ] 19:12:17 Set vmware modules
sed: can't read /mnt/etc/mkinitcpio.conf: No such file or directory
[ INFO ] 19:12:17 Set mkinitcpio hooks
[ INFO ] 19:12:17 Copy /etc/skel/.bashrc to /mnt/etc/skel/.bashrc
[ [38;5;196mERROR[0m ] 19:12:17 Copy /mnt/usr/lib/os-release-athena to /mnt/usr/lib/os-release: Failed with error No such file or directory (os error 2)

**Comment by D3vil0p3r** [comment]
Need the entire /tmp/aegis.log file

**Comment by HHhne** [comment]
[aegis.log](https://github.com/Athena-OS/athena-iso/files/13938735/aegis.log)

**Comment by HHhne** [comment]
[Uploading aegis.log…]()
new

**Comment by D3vil0p3r** [comment]
@Mohadib2 the new ISO does not use those keys anymore. Get it by https://github.com/Athena-OS/athena/releases/tag/v23.11

**Comment by h4ckj0urn3y** [comment]
Hi all,
I’m currently running a dual-boot setup with Arch Linux and Kali Linux on one SSD, and Windows on a second SSD. All of these OSes are managed using GRUB as the bootloader, and everything is working fine so far. However, I’m now trying to add Athena OS alongside Windows on the second SSD, but I’m running into an issue during installation, and I can’t seem to resolve it despite following the official documentation.
System Setup:
SSD 1: Arch Linux + Kali Linux
SSD 2: Windows 10 (currently installed)
Bootloader: GRUB managing all 3 OSes.
Athena OS installation target: Second SSD (same SSD as Windows)
Steps Followed:
Partitioning the Second SSD: I’ve partitioned the second SSD where Windows is installed, ensuring there’s enough space for Athena OS.
Running Athena OS Installer: I’ve booted from the Athena OS live USB, selected the root partition on the second SSD, and pointed the installer to the existing boot partition located on SSD 1 (the first SSD where Arch/Kali are installed).
GRUB Configuration: I’ve tried pointing the Athena OS installer to the existing boot partition on SSD 1, where GRUB is located. I thought this would keep everything centralized on SSD 1.
Error Encountered:
While running the installation script, I’m getting the following error:Error Encountered:While running the installation script, I’m getting the following error:
================================================================
[ INFO ] 11:41:40 checking keyring...
[ INFO ] 11:41:40 checking package integrity...
[ INFO ] 11:42:06 loading package files...
[ INFO ] 11:42:07 checking for file conflicts...
[ INFO ] 11:42:10 error: failed to commit transaction (conflicting files)
[ INFO ] 11:42:10 amd-ucode: /mnt/boot/amd-ucode.img exists in filesystem
[ INFO ] 11:42:10 Errors occurred, no packages were upgraded.
[ INFO ] 11:42:10 ==> ERROR: Failed to install packages to new root
[ ERROR ] 11:42:10 The package manager failed with exit code: 1
[ INFO ] 11:42:10 Copy /etc/pacman.d/mirrorlist to /mnt/etc/pacman.d/mirrorlist
[ INFO ] 11:42:10 Copy /etc/pacman.d/chaotic-mirrorlist to /mnt/etc/pacman.d/chaotic-mirrorlist
[ INFO ] 11:42:10 The system has 16 cores
[ INFO ] 11:42:10 Sed '#MAKEFLAGS=.*' to 'MAKEFLAGS="-j16"' in file /mnt/etc/makepkg.conf
[ INFO ] 11:42:10 Set available cores on MAKEFLAGS ERROR: No such file or directory (os error 2)
[ ERROR ] 11:42:10 Set available cores on MAKEFLAGS ERROR: No such file or directory (os error 2)
Do you want to generate logs of the failed install to communicate to the team? (Y/n) n
=============================================================================
The issue seems to be related to a file conflict during the installation process. Specifically, the error mentions /mnt/boot/amd-ucode.img already existing in the filesystem.

Is the error caused by having the boot partition located on SSD 1 (different from the installation target on SSD 2)?
Should I try installing Athena OS with a separate boot partition on SSD 2?
What would be the best approach to resolve the file conflict (amd-ucode.img) issue during installation?
Any help or advice on how to troubleshoot this issue would be greatly appreciated!
Thanks in advance for your time!
